### PR TITLE
Remove function names

### LINKED ISSUE #46: Throws an error in Safari
When running my web-app in Safari I gain the following error:

SyntaxError: Cannot declare a parameter named 'mask' as it shadows the name of a strict mode function.

 ip.mask = function mask(addr, mask) 

seems the issues is wide-spread - 
https://github.com/mishoo/UglifyJS2/issues/179 
https://github.com/ipfs/js-ipfs-api/issues/124

### PR DESCRIPTION
**Pull request by vkramskikh**
Named function 'mask' causes strict mode violation in Safari:

SyntaxError: Cannot declare a parameter named 'mask' as it shadows
the name of a strict mode function.

Fixes #46

### CODE REVIEW

**Comment by bryanwayb** [comment]
Hi! Thanks for the PR. Looks good to me, so I've merged.

**Comment by vkramskikh** [comment]
@bryanwayb Thanks! Is version bump planned?

**Comment by joaocunha** [comment]
:+1: on version bump. We need it over here, too.

Thanks for the fix.

**Comment by pfraze** [comment]
Hey, this is hitting us in @ssbc. What's the word on a patch bump?

**Comment by bryanwayb** [comment]
@pfraze Good question. Hey @indutny, could we get a version bump please? Looks like this was merged right after the last release.

**Comment by klyngbaek** [comment]
+1 on version bump.

**Comment by indutny** [comment]
Done!

**Comment by bryanwayb** [comment]
Thanks!

**Pull request merged**
