### PR TITLE
Add support for IPv4-mapped IPv6 addresses

### PR DESCRIPTION
**Pull request by ym**
http://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses

### CODE REVIEW

**Comment by razvanz** [comment]
+1 Another description provided by [IBM](http://www-01.ibm.com/support/knowledgecenter/STCMML8/com.ibm.storage.ts3500.doc/opg_3584_IPv4_IPv6_addresses.html)

**Comment by indutny** [comment]
Sorry for a late response! :) The change is looking good to me! Would you mind providing a test for it?

**Comment by razvanz** [comment]
According to [IBM](http://www-01.ibm.com/support/knowledgecenter/STCMML8/com.ibm.storage.ts3500.doc/opg_3584_IPv4_IPv6_addresses.html) the IPv6 Dual format is composed from a IPv6 Normal + IPv4. like `2001 : db8: 3333 : 4444 : 5555 : 6666 : 1 . 2 . 3 . 4` or `: : 1234 : 5678 : 1 . 2 . 3 . 4`. This pull request only checks for `::ffff:` in front of the IPv4 which does not cover all the cases.
The only thing I haven't understood is which of the IPv6 vs IPv4 addresses should be considered and which should be ignored?

**Comment by indutny** [comment]
@razvanz I don't think that IBM is a sole authority on this, I'd rather trust: https://tools.ietf.org/html/rfc4291#section-2.5.5.2

**Comment by razvanz** [comment]
You're absolutely right. IBM was the reference I found :)

[RFC4038](https://tools.ietf.org/html/rfc4038#section-4.2):
> IPv4-mapped IPv6 addresses: the IPv6 address ::FFFF:x.y.z.w represents the IPv4 address x.y.z.w.

Considering this, the solution is valid, though `ip.isPublic` and `ip.isLoopback` functions would need to be updated as well.

**Comment by indutny** [comment]
So, to conclude: this change needs a test ;)

**Comment by ilkkao** [comment]
Added some test in https://github.com/indutny/node-ip/pull/29/

**Comment by indutny** [comment]
Landed in #29

**Pull request closed without merging**
